version: '3.1'

services:
  app:
    image: "sha256:b5130fa4de9ea1cc93046511544f5a166609c539daf9cd13fb3d6e27df619446"
    container_name: app
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/postgres
    depends_on:
      - db
  db:
    image: 'postgres'
    container_name: 'db'
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: